mdapi/objects/ltng_TileLauncherEntry__c.object
<CustomObject>
    <description>Tile that can launch a page / url / record within salesforce - customizable by the end user.</description>
    <label>Tile Launcher Entry</label>
    <nameField>
        <label>Tile Launcher Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tile Launcher Entries</pluralLabel>
    <sharingModel>Read</sharingModel>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Description for what this link represents</inlineHelpText>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Used in data loading and updates.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique Id for the icon.</inlineHelpText>
        <label>External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IconGroup__c</fullName>
        <inlineHelpText>The Lightning Design System icon group.
https://www.lightningdesignsystem.com/icons/
Standard is used if not set.</inlineHelpText>
        <label>Icon Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>standard</fullName>
                </value>
                <value>
                    <fullName>custom</fullName>
                </value>
                <value>
                    <fullName>action</fullName>
                </value>
                <value>
                    <fullName>doctype</fullName>
                </value>
                <value>
                    <fullName>utility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IconName__c</fullName>
        <description>List of all icons are available here:
https://www.lightningdesignsystem.com/icons/#standard</description>
        <inlineHelpText>Standard Lightning Icon name (or blank if no icon should be used):

https://www.lightningdesignsystem.com/icons</inlineHelpText>
        <label>Icon Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permission__c</fullName>
        <inlineHelpText>Name of the custom permission that is required for the user to see this link.</inlineHelpText>
        <label>Permission</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredSortIndex__c</fullName>
        <inlineHelpText>Lowest number QuickLink appears at the top (those without towards the bottom)</inlineHelpText>
        <label>Preferred Sort Index</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <description>Can be URL Schemes, partial urls, etc.</description>
        <inlineHelpText>Target address to direct the user to when clicking the tile.</inlineHelpText>
        <label>Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Please note that the Visualforce page can include URL Parameters.</description>
        <inlineHelpText>Whether the target is a Record Id, Visualforce page, URL, etc.</inlineHelpText>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>URL</fullName>
                </value>
                <value>
                    <fullName>Knowledge Article</fullName>
                </value>
                <value>
                    <fullName>Named Page</fullName>
                </value>
                <value>
                    <fullName>Navigation Item Page</fullName>
                </value>
                <value>
                    <fullName>Object Page</fullName>
                </value>
                <value>
                    <fullName>Record Page</fullName>
                </value>
                <value>
                    <fullName>Record Relationship Page</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

mdapi/objects/ltng_TileLauncherEntryPreference__c.object
<CustomObject>
    <description>User preference for a Tile Launcher Entry.
(Sort order or whether it is hidden or not, etc)</description>
    <label>Tile Launcher Entry Preference</label>
    <nameField>
        <displayFormat>tlep-{00000}</displayFormat>
        <label>Tile Launcher Entry Preference Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tile Launcher Entry Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>PreferredSortIndex__c</fullName>
        <inlineHelpText>Lowest number QuickLink appears at the top (those without towards the bottom)</inlineHelpText>
        <label>Preferred Sort Index</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TileLauncherEntry__c</fullName>
        <inlineHelpText>The tile Launcher Entry this relates to.</inlineHelpText>
        <label>Tile Launcher Entry</label>
        <referenceTo>ltng_TileLauncherEntry__c</referenceTo>
        <relationshipLabel>Tile Launcher Entry Preferences</relationshipLabel>
        <relationshipName>ltng_TileLauncherPreference</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>UniqueId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for the junction (used to simplify creation/updates)</inlineHelpText>
        <label>Unique Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>User this preference is for</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ltng_TileLauncherPreference</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi/objects/ltng_TileLauncherNavigationFormat__mdt.object
<CustomObject>
    <description>Format for a url to provide navigation for Tiles in the Tile Launcher</description>
    <label>Tile Launcher Navigation Format</label>
    <pluralLabel>Tile Launcher Navigation Formats</pluralLabel>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Description of this pattern / what it is this meant to match</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Navigation_Object_Format__c</fullName>
        <inlineHelpText>Format of the navigation object (using matches from the URL Format)</inlineHelpText>
        <label>Navigation Object Format</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Navigation_Type__c</fullName>
        <description>For more information, please see:
https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/components_navigation_page_definitions.htm</description>
        <inlineHelpText>Knowledge Article - Knowledge Article
Named Page - access: &#39;home&#39;, &#39;chatter&#39;, &#39;today&#39;
Navigation Item - Custom Tab
Object Page - Recent or list views for an object
Record Page - Directly access a record
Record Relationship Page - Related List</inlineHelpText>
        <label>Navigation Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Knowledge Article</fullName>
                    <default>true</default>
                    <label>Knowledge Article</label>
                </value>
                <value>
                    <fullName>Named Page</fullName>
                </value>
                <value>
                    <fullName>Navigation Item Page</fullName>
                </value>
                <value>
                    <fullName>Object Page</fullName>
                </value>
                <value>
                    <fullName>Record Page</fullName>
                </value>
                <value>
                    <fullName>Record Relationship Page</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <defaultValue>100</defaultValue>
        <inlineHelpText>Items with higher priority are checked first.
(The first one that matches, will be used)</inlineHelpText>
        <label>Priority</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>URL_Format__c</fullName>
        <inlineHelpText>Regular expression for this pattern</inlineHelpText>
        <label>URL Format</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
</CustomObject>

mdapi/classes/ltng_TileLauncherCtrl.cls
/**
 * Server side controller for the Tile Launcher
 **/
public with sharing class ltng_TileLauncherCtrl {

	/**
	 *  Determines the list of Tiles available to the user.
	 *  @return (ltng_TileLauncherEntry__c)
	 **/
	@AuraEnabled
	public static ltng_TileLauncherEntry__c[] getMyLinks(){
		ltng_TileLauncherEntry__c[] results = new ltng_TileLauncherEntry__c[]{};
		
		return( getLinks( UserInfo.getUserId() ));
	}
	
	/**
	 *  Determines the list of Tiles available to a specific person.
	 *  @param userId (Id)
	 *  @return (ltng_TileLauncherEntry__c[])
	 **/
	public static ltng_TileLauncherEntry__c[] getLinks( Id userId ){
		ltng_TileLauncherEntry__c[] results = new ltng_TileLauncherEntry__c[]{};
		
		//-- @TODO: add try catch in after completed
		//try {
		
		//-- set of all custom permissions to check for
		Set<String> allTilePermissions = new Set<String>();
		//-- map of all quicklinks grouped by custom permission developer name
		Map<String,ltng_TileLauncherEntry__c[]> tilesByPermission = new Map<String,ltng_TileLauncherEntry__c[]>();
		//-- ids of all the permission sets that contain those custom permissions
		//-- translation of all custom permissions developer names into their ids
		Map<Id,String> customPermissions = new Map<Id,String>();
		//-- collection of all custom permissions requested with the list of permission sets that contain them.
		Map<Id,String[]> permissionSetPermissions = new Map<Id,String[]>();
		//-- collection of all the user specific preferences
		Map<Id,Decimal> tileSortPreferenceMap = new Map<Id,Decimal>();

		//-- determine the user sort preferences
		for( ltng_TileLauncherEntryPreference__c tilePreference : [
			SELECT Id, TileLauncherEntry__c, PreferredSortIndex__c
			FROM ltng_TileLauncherEntryPreference__c
			WHERE User__c = :userId
		]){
			tileSortPreferenceMap.put(tilePreference.TileLauncherEntry__c, tilePreference.PreferredSortIndex__c);
		}
		
		//-- determine all quicklinks and sort them by the permission required to see them.
		ltng_TileLauncherEntry__c[] allTiles = [ select id, name, Description__c, ExternalId__c, IconGroup__c, IconName__c, Type__c, Target__c, Permission__c, PreferredSortIndex__c, LastModifiedDate
			from ltng_TileLauncherEntry__c
			order by PreferredSortIndex__c NULLS LAST, name
		];
		
		for( ltng_TileLauncherEntry__c tile : allTiles ){

			//-- update the sort order
			if( tileSortPreferenceMap.containsKey(tile.Id) ){
				tile.PreferredSortIndex__c = tileSortPreferenceMap.get(tile.Id);
			}

			if( String.isEmpty( tile.Permission__c )){
				results.add( tile );
			} else {
				if( !tilesByPermission.containsKey( tile.Permission__c )){
					tilesByPermission.put( tile.Permission__c, new ltng_TileLauncherEntry__c[]{} );
				}
				tilesByPermission.get( tile.Permission__c ).add( tile );
			}
		}
		
		//-- @INVARIANT: all quicklinks have been recieved, and are now grouped by custom permission developer name within a map.
		allTilePermissions = tilesByPermission.keySet();
		//System.debug( 'allTilePermissions:' + allTilePermissions );
		
		//-- create a translation for all custom permission DeveloperNames to their IDs
		for( CustomPermission perm: [
			SELECT Id, DeveloperName FROM CustomPermission WHERE DeveloperName in :allTilePermissions
		]){
			customPermissions.put( perm.Id, perm.DeveloperName );
		}
		
		//System.debug( 'customPermissionsMap:' + customPermissions );
		//-- collect all permission sets by custom permission developer name
		String permissionName;
		for( SetupEntityAccess access: [
			SELECT SetupEntityId, ParentId FROM SetupEntityAccess WHERE SetupEntityId in (
				SELECT Id FROM CustomPermission WHERE DeveloperName in :allTilePermissions
			)
		]){
			if( !permissionSetPermissions.containsKey( access.ParentId )){
				permissionSetPermissions.put( access.ParentId, new String[]{} );
			}
			permissionName = customPermissions.get( access.SetupEntityId );
			permissionSetPermissions.get( access.ParentId ).add( permissionName );
		}
		
		//-- @INVARIANT: we now have a list of all permissionSets with the custom permissions that they contain.
		//System.debug( 'permissionSetPermissions:' + permissionSetPermissions );
		
		//-- determine all the custom permissions that the user has
		Set<String> userCustomPermissions = new Set<String>();
		for( PermissionSetAssignment assignment: [
			SELECT PermissionSetId FROM PermissionSetAssignment where AssigneeId = :userId
		]){
			//System.debug( 'permissionSet[' + assignment.PermissionSetId + ']:' + permissionSetPermissions.get( assignment.PermissionSetId ) );
			if( permissionSetPermissions.containsKey( assignment.PermissionSetId )){
				userCustomPermissions.addAll( permissionSetPermissions.get( assignment.PermissionSetId ) );
			}
		}
		
		//-- @INVARIANT - we now know all the custom permissions that the user belongs to.
		//System.debug( 'userCustomPermissions:' + userCustomPermissions );
		
		for( String userCustomPermission : userCustomPermissions ){
			results.addAll( tilesByPermission.get( userCustomPermission ));
		}
		
		//System.debug( 'results:' + results );
		
		//} catch( Exception err ){}
		
		return( results );
	}

	/**
	 * Save all the user order settings
	 * <p>Either we can save them all in one swoop, like this,
	 *  or we can save them peicemeal as they happen.</p>
	 * <p>There was concern with how much api usage it would consume
	 *  (and how noisy it would be)
	 *  so all in one swoop was chosen.</p>
	 * <p>But there is lingering concern with how many preferences
	 *  would need to be saved / especially with a larger set of tiles.</p>
	 * @param ltng_TileLauncherEntryPreference__c[]
	 * return {boolean}
	 **/
	@AuraEnabled
	public static ltng_TileLauncherEntryPreference__c[] saveTilePreferences(String tilePreferencesJSON) {

		System.debug('tilePreferencesJSON'); System.debug(tilePreferencesJSON);
		/*
		There is a known issue on this, where we cannot accept an array of SObjects.
		https://success.salesforce.com/issues_view?id=a1p3A000000EAbLQAW&title=passing-an-apex-custom-object-parameter-type-from-an-aura-component-to-an-apex-controller-throws-an-error

		Currently the parser says that this will not work:
		[{"PreferredSortIndex__c":4,"TileLauncherEntry__c":"a005B000001wgzYQAQ"},
		{"PreferredSortIndex__c":5,"TileLauncherEntry__c":"a005B000001wgzcQAA"}];
		but adding in an ID WILL work
		[{"Id":"a015B0000076jDYQAY","PreferredSortIndex__c":4,"TileLauncherEntry__c":"a005B000001wgzYQAQ"},
		{"Id":"a015B0000076jCuQAI","PreferredSortIndex__c":5,"TileLauncherEntry__c":"a005B000001wgzcQAA"}]

		Unfortunately, it cannot be any valid Id,
		but that the shortId must be valid - and the IDs must be unique.
		so this WOULD work:
		[{"Id":"a01000000000000001","PreferredSortIndex__c":4,"TileLauncherEntry__c":"a005B000001wgzYQAQ"},
		{"Id":"a01000000000000001","PreferredSortIndex__c":5,"TileLauncherEntry__c":"a005B000001wgzcQAA"}]
		This doesn't make that easy if we are upserting records, as we would have to generate the ID
		and then clear it out prior to saving.  This isn't always allowed.

		SO THE CURRENT KLUDGE is that we need to store it in JSON and then deserialize it here.

		We do this through the TilePreferenceCollection and TilePreference classes below...
		*/

		TilePreferenceCollection tilePreferences = ((TilePreferenceCollection)System.JSON.deserialize(tilePreferencesJSON, TilePreferenceCollection.class));

		Id currentUserId = UserInfo.getUserId();
		System.debug('userId:' + currentUserId);
		System.debug('tilePreferences'); System.debug(tilePreferences);
		System.debug('tilePreferences.length:' + tilePreferences.records.size());

		ltng_TileLauncherEntryPreference__c[] recordsToUpdate = new ltng_TileLauncherEntryPreference__c[]{};
		ltng_TileLauncherEntryPreference__c newPreference;
		
		for(TilePreference tilePreference : tilePreferences.records){
			newPreference = new ltng_TileLauncherEntryPreference__c(
				TileLauncherEntry__c = tilePreference.tileLauncherEntryId,
				PreferredSortIndex__c = Decimal.valueOf(tilePreference.preferredSortIndex),
				User__c = currentUserId,
				UniqueId__c = currentUserId + '-' + tilePreference.tileLauncherEntryId
			);

			recordsToUpdate.add(newPreference);
		}

		System.debug(recordsToUpdate);

		Schema.SObjectField uniqueIdField = ltng_TileLauncherEntryPreference__c.UniqueId__c.getDescribe().getSObjectField();
		
		//try {
			Database.upsert(recordsToUpdate, uniqueIdField, true);
		//} catch(Exception err){
		//	throw new AuraHandledException('Exception occurred when processing: saveTilePreferences');
		//}
		
		return(recordsToUpdate);
	}

	public class TilePreferenceCollection {
		@AuraEnabled
		public TilePreference[] records {get;set;}
	}

	public class TilePreference {
		@AuraEnabled
		public string tileLauncherEntryId {get;set;}

		@AuraEnabled
		public double preferredSortIndex {get;set;}
	}
	

	/**
	 * Determines the tile launcher formats.
	 * @return ltng_TileLauncherNavigationFormat__mdt[] - collection of tile launcher navigation formats.
	 **/
	 @AuraEnabled
	 public static ltng_TileLauncherNavigationFormat__mdt[] getLauncherFormats() {
		ltng_TileLauncherNavigationFormat__mdt[] results;

		//-- @TODO: review only retrieving formats that match an object format
		//-- but this is cleaner and expected to be fairly small in number.
		try {
			results = [
				SELECT id, DeveloperName, Navigation_Type__c, Navigation_Object_Format__c, URL_Format__c, Priority__c
				FROM ltng_TileLauncherNavigationFormat__mdt
				ORDER BY Navigation_Type__c, Priority__c desc
			];		 
		} catch(Exception err){
			throw new AuraHandledException('Exception occurred when processing: getLauncherFormats');
		}

		return(results);
	 }
}